Respect $fish_history environment variable
jbonjean/re-search pull request #27
Opened 2021-03-10 21:29 UTC by hupfdule

If `$fish_history` is set, use it to construct the name of the fish
history file.
The behaviour of `$fish_history` is described in
https://fishshell.com/docs/current/cmds/history.html#customizing-the-name-of-the-history-file.

Additionally the actual error is printed if opening the history file failed.

2021-03-18 03:26 UTC, jbonjean requested changes
I started the review, but I think this needs to be reworked, at least the bash support, which I think didn't actually need any change.

2021-03-18 03:26 UTC, jbonjean commented on re-search.c
> +	histpath = "."
Missing semicolon.

2021-03-18 03:26 UTC, jbonjean commented on re-search.c
> +	histfile = ".bash_history";
You cannot assign a char array like that.

2021-03-18 03:26 UTC, jbonjean commented on re-search.c
> +	snprintf(histfile, sizeof(histfile), ".bash_history", fish_session);
fish_session is not defined here.

2021-04-08 09:38 UTC, hupfdule commented
You are right, I forgot to correctly adapt the bash history loading and left it in a broken state.

As I decided to maintain my own fork, I will close this PR as well.

2021-04-08 09:38 UTC, closed without merging